Update example code in timeseries_dataset.py
keras-team/tf-keras pull request #14
Opened 2023-09-20 06:48 UTC by SuryanarayanaY

I have gone through the example-2 in the TF documentation of [keras.utils.timeseries_dataset_from_array](https://www.tensorflow.org/api_docs/python/tf/keras/utils/timeseries_dataset_from_array). With existing code we can only generate one batch of dataset.In TF forum one of the user raised concern that users may confuse why we are using `input_data = data[:-10]` as it can generate only one batch and there will be loss of data and users may confuse `-10` as `sequence_length` here. Though the intention in the example is to demo on generating batches of data using the API,Its better to use `input_data = data[:]` to avoid confusion and also it give correct demo to generate the total possible no of batches without loss of data.

Also I am adding the `sequence_length` as variable in the code to avoid hard coding in the data indexing which will make it better understandable.

Thanks!

2023-09-28 15:15 UTC, grasskin requested changes
I think overall it's a helpful change - thank you for the PR!

2023-09-28 15:15 UTC, grasskin commented on tf_keras/utils/timeseries_dataset.py
> +    sequence_length =10
Make sure to run the formatter (add a space before 10)

2023-10-31 05:55 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @grasskin's comments ? Thank you!

2023-11-06 07:16 UTC, SuryanarayanaY commented
Done the changes for black formatting.Please review.

2024-01-08 12:49 UTC, grasskin approved these changes
LGTM, thank you!

2024-07-29 18:06 UTC, merged